name: first workflow

on:
  push:
    branches:
      - "main"
  # pull_request:
  #   branches:
  #     - main
  #   types: [opened,closed]

jobs:
  first-workflow-job:
    name: first-job
    runs-on: ubuntu-latest
    container:
      image: node:14.16
    steps:
      #  - name: before checkout
      #    run: ls
      #    shell: bash

      #  - name: checkout action
      #    uses: actions/checkout@v4

      #  - name: after checkout
      #    run: ls
      #    shell: bash
      - name: print node version
        run: node -v