name: repo-dispatch-workflow

on:
  repository_dispatch:
    types: [build]

jobs:
    repo-task-job:
      name: repo-job
      runs-on: ubuntu-latest
      steps:
        - run: echo "repo dispatch event"
