name: testing workflow dispatch

on:
  workflow_dispatch:
    inputs:
        VersionName:
          required: true
          description: "this is version number to be released"
        
jobs:
    testing-workflow-dispatch:
      name: testing workflow dispatch
      runs-on: ubuntu-latest
      steps:
        - name: testing workflow-dispatch
          if: github.event.inputs.VersionName == 'build'
          run: echo "workflow dispatch"